---
destination : /Users/dess-e/rails/dessy
auto        : false
lsi         : false
pygments    : true
permalink   : /:year/:month/:day/:title/
markdown    : maruku
future      : true
maruku:
    use_divs: true
